### ISSUE TITLE
Missing ecpr invariant

### ISSUE THREAD

**Issue by jkiddo** [medcomdk/dk-medcom-core#12]
eCPR does not contain an invariant that guards that the rules on https://cpr.dk/cpr-systemet/erstatningspersonnummer-i-eksterne-systemer are followed

**Comment by tmsMedcom** [comment]
Good point! We will take a look at it.

**Comment by tmsMedcom** [comment]
Updated the dependency to DkCore v.3.2.0 in next release. It will handle this issue.
